# Generated by Django 4.2.6 on 2023-10-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pudlished_date',
            new_name='published_date',
        ),
    ]
